name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --build-arg BRANCH=${GITHUB_REF##*/} --file Dockerfile --tag daler-dotfiles

    - name: Test the docker image
      run: |
        cd tests
        bash run-tests.sh
